# Generated by Django 5.1.2 on 2024-10-31 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='service_types',
        ),
        migrations.DeleteModel(
            name='ServiceType',
        ),
    ]
