# Generated by Django 5.1.2 on 2024-10-31 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arl', '0001_initial'),
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('identify', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('resource_hours', models.IntegerField(null=True)),
                ('expiration_date', models.DateField(null=True)),
                ('date_radicate', models.DateField(null=True)),
                ('arl', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arls', to='arl.arl')),
                ('company', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='company.company')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
                ('classification', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='tracking.trackingclassification')),
                ('state', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state', to='tracking.trackingstate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
