# Generated by Django 5.1.2 on 2024-10-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_servicetype_tracking_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='asigned_resource',
            field=models.IntegerField(null=True),
        ),
    ]
